//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevToys.JsonQuery {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JsonQueryResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonQueryResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DevToys.JsonQuery.JsonQueryResources", typeof(JsonQueryResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jq runner extension for DevToys to run queries against json structures.
        /// </summary>
        public static string AccessibleName {
            get {
                return ResourceManager.GetString("AccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array construction.
        /// </summary>
        public static string CheatSheetArrayConstruction {
            get {
                return ResourceManager.GetString("CheatSheetArrayConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array-Index.
        /// </summary>
        public static string CheatSheetArrayIndex {
            get {
                return ResourceManager.GetString("CheatSheetArrayIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array/Object Value Iterator.
        /// </summary>
        public static string CheatSheetArrayObjectValueIterator {
            get {
                return ResourceManager.GetString("CheatSheetArrayObjectValueIterator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concatenation.
        /// </summary>
        public static string CheatSheetConcatenation {
            get {
                return ResourceManager.GetString("CheatSheetConcatenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string CheatSheetDescription {
            get {
                return ResourceManager.GetString("CheatSheetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example.
        /// </summary>
        public static string CheatSheetExample {
            get {
                return ResourceManager.GetString("CheatSheetExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string CheatSheetIdentity {
            get {
                return ResourceManager.GetString("CheatSheetIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object construction.
        /// </summary>
        public static string CheatSheetObjectConstruction {
            get {
                return ResourceManager.GetString("CheatSheetObjectConstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Identifier-Index.
        /// </summary>
        public static string CheatSheetObjectIdentifierIndex {
            get {
                return ResourceManager.GetString("CheatSheetObjectIdentifierIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Index.
        /// </summary>
        public static string CheatSheetObjectIndex {
            get {
                return ResourceManager.GetString("CheatSheetObjectIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional Object Identifier-Index.
        /// </summary>
        public static string CheatSheetOptionalObjectIdentifierIndex {
            get {
                return ResourceManager.GetString("CheatSheetOptionalObjectIdentifierIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe.
        /// </summary>
        public static string CheatSheetPipe {
            get {
                return ResourceManager.GetString("CheatSheetPipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax.
        /// </summary>
        public static string CheatSheetSyntax {
            get {
                return ResourceManager.GetString("CheatSheetSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jq Cheat Sheet.
        /// </summary>
        public static string CheatSheetTitle {
            get {
                return ResourceManager.GetString("CheatSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A jq runner extension for DevToys to run queries against json structures.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 Spaces.
        /// </summary>
        public static string FourSpaces {
            get {
                return ResourceManager.GetString("FourSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation.
        /// </summary>
        public static string Indentation {
            get {
                return ResourceManager.GetString("Indentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file selected doesn&apos;t exist..
        /// </summary>
        public static string InputFileNotFound {
            get {
                return ResourceManager.GetString("InputFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text or path to a file containing the JSON.
        /// </summary>
        public static string InputJsonOptionDescription {
            get {
                return ResourceManager.GetString("InputJsonOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text or path to a file containing the jq query.
        /// </summary>
        public static string InputJsonQueryOptionDescription {
            get {
                return ResourceManager.GetString("InputJsonQueryOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jq Query.
        /// </summary>
        public static string InputJsonQueryTitle {
            get {
                return ResourceManager.GetString("InputJsonQueryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input JSON.
        /// </summary>
        public static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify an input text or an input file.
        /// </summary>
        public static string InvalidInputOrFileCommand {
            get {
                return ResourceManager.GetString("InvalidInputOrFileCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Query.
        /// </summary>
        public static string LongDisplayTitle {
            get {
                return ResourceManager.GetString("LongDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minified.
        /// </summary>
        public static string Minified {
            get {
                return ResourceManager.GetString("Minified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found.
        /// </summary>
        public static string NoMatchFound {
            get {
                return ResourceManager.GetString("NoMatchFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Tab.
        /// </summary>
        public static string OneTab {
            get {
                return ResourceManager.GetString("OneTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the output file.
        /// </summary>
        public static string OutputFileOptionDescription {
            get {
                return ResourceManager.GetString("OutputFileOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to json query jq.
        /// </summary>
        public static string SearchKeywords {
            get {
                return ResourceManager.GetString("SearchKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Query.
        /// </summary>
        public static string ShortDisplayTitle {
            get {
                return ResourceManager.GetString("ShortDisplayTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Keys.
        /// </summary>
        public static string SortKeys {
            get {
                return ResourceManager.GetString("SortKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 Spaces.
        /// </summary>
        public static string TwoSpaces {
            get {
                return ResourceManager.GetString("TwoSpaces", resourceCulture);
            }
        }
    }
}
